name: Create Docker image (Stable)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Latest version'
        required: true
        type: string

jobs:
  deploy:
    runs-on: alpine
    steps:
    - name: Setup Alpine 
      uses: https://git.swee.codes/swee/setup-alpine@main
      with:
        additional: docker curl
    - uses: actions/checkout@v3
      with:
        ref: stable
    - name: Start daemon
      run: dockerd &
    - name: Download dockerfile
      run: curl https://git.swee.codes/swee/IRCat/raw/branch/main/Dockerfile > Dockerfile
    - name: Login to Docker
      run: echo ${{ secrets.TOKEN }} | docker login git.swee.codes --username swee --password-stdin
    - name: Build docker image
      run: docker build -t git.swee.codes/swee/ircat:latest -t git.swee.codes/swee/ircat:${{ inputs.version }} .
    - name: Push docker image
      run: docker push git.swee.codes/swee/ircat --all-tags